### ISSUE TITLE
Doesn't seem to load host projects .babelrc

### ISSUE THREAD

**Issue by mattberkowitz** [marijnh/moduleserve#1]
See https://github.com/ProseMirror/prosemirror/issues/143.

In order to get it working with prosemirror, I modified babel-transform.js:15 to be

```
return babel.transform(text, {presets:['es2015']}).code
```

**Comment by marijnh** [comment]
That is very ProseMirror-specific, though. At some point, babel-core was automatically reading the `.babelrc` for the project, which was much preferable, because it means it would work for other projects as well. The babel docs are kind of useless, and I haven't yet found out when and how it reads that config file.

**Comment by marijnh** [comment]
Attached patch solves this -- it tells Babel about the filename, which causes it to find the config file.

**Comment by mattberkowitz** [comment]
Great, thanks!
