### ISSUE TITLE
Resolving fails for a moudule with two folders up dependency

### ISSUE THREAD

**Issue by ericandrewlewis** [marijnh/moduleserve#5]
I've modified the ProseMirror demo to [require a module](https://gist.github.com/ericandrewlewis/5f125798f31958be1374#file-demo-js-L5) for an experiment.

The module has a dependency on a module in ProseMirror, [so I import it accordingly](https://gist.github.com/ericandrewlewis/5f125798f31958be1374#file-src-lockedblock-js-L1). I run this through babel via `./node_modules/.bin/babel -d demo/dist demo/src`, which gets required by the demo's main script.

The name `../../dist/model` ends up being resolved to `/dist/dist/model`, where I might expect it to resolve to `/../dist/model`.

I tried debugging why this is happening inside [the resolving code](https://github.com/marijnh/moduleserve/blob/master/client.js#L21-L28), but I'm not sure what would need to change to support this.

**Comment by marijnh** [comment]
Is your `"./dist/lockedblock"` path correct? (Because the other imports in that file are talking about `../dist`.) There's plenty of `../..` in the browser tests (for example `src/test/browser/def.js`) where it doesn't cause any problems.

Could you create a more complete/self-sufficient description of the problem? I don't really understand where the various files in your gist are supposed to be.

**Comment by ericandrewlewis** [comment]
Here's [the example](https://github.com/ericandrewlewis/prosemirror/commit/00c60a254233fd055577eede58607a2d56d259fc) using the PM demo.

**Comment by marijnh** [comment]
Ah, now I see. Attached patch should help. Can you confirm that it solves your issue? I'll do a release.

**Comment by ericandrewlewis** [comment]
That did it. Thanks!

**Comment by marijnh** [comment]
Published as 0.7.1
